.TH hifiberry-bluetooth 1
.SH NAME
hifiberry-bluetooth \- Manage Bluetooth connections
.SH SYNOPSIS
.B hifiberry-bluetooth
.SH DESCRIPTION
Manages how Bluetooth connections will work. Set the different options using
either the web interface of hbos or using the config file.

This should be a daemon but it can be run by the user.
.SH EXAMPLES
.TP
Start the application:
.B hifiberry-bluetooth
.SH AUTHORS
HiFiBerry Support <support@hifiberry.com>
.SH COPYRIGHT
Copyright (c) 2025 HiFiBerry. Licensed under the MIT License.


